name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    
permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.8.6
